name: Trigger Add Resources

on:
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  trigger_add_resources:
    runs-on: ubuntu-latest
    steps:
      - name: Check Out Repository
        uses: actions/checkout@v2
        with:
          fetch-depth: 0 

      - name: Set Files Variable
        id: files
        run: |
          echo "##[group]Extracting modified files"
          FILES=$(git diff --name-only ${{ github.event.pull_request.base.sha }} ${{ github.event.pull_request.head.sha }} | jq -R -s -c 'split("\n") | map(select(length > 0))')
          
          # Construct full GitHub URL for each file, and URL encode spaces
          FULL_URLS=$(echo "$FILES" | while read -r FILE; do
            ENCODED_FILE=$(echo "$FILE" | sed 's/ /%20/g')
            echo "https://github.com/UBB-resources-project/Resources/blob/test_add_resources/$ENCODED_FILE"
          done | jq -R -s -c 'split("\n") | map(select(length > 0))')
          
          echo "FULL_URLS=$FULL_URLS"
          echo "##[endgroup]"
          echo "::set-output name=files::$FULL_URLS"

      - name: Trigger Send Resource
        run: |
          FILES=${{ steps.files.outputs.files }}
          echo "Files to be sent: $FILES"

          # Pass the files as a string, ensuring it is quoted properly
          curl -X POST \
            -H "Authorization: token ${{ secrets.MY_GITHUB_TOKEN }}" \
            -H "Accept: application/vnd.github.v3+json" \
            https://api.github.com/repos/UBB-resources-project/website_ubb/actions/workflows/add_resources.yml/dispatches \
            -d "{\"ref\": \"workflow_resources\", \"inputs\": {\"files\": \"$FILES\"}}"
