name: Trigger Add Resources

on:
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  trigger_add_resources:
    runs-on: ubuntu-latest
    steps:
      - name: Check Out Repository
        uses: actions/checkout@v2
        with:
          fetch-depth: 0 
          
      - name: Set Files Variable
        id: files
        run: |
          echo "##[group]Extracting modified files"
          FILES=$(git diff --name-only ${{ github.event.pull_request.base.sha }} ${{ github.event.pull_request.head.sha }} | tr '\n' ' ')

          echo "FILES=$FILES"
          echo "##[endgroup]"
      
          # Write the files to a text file
          echo "$FILES" > files_to_send.txt
          cat files_to_send.txt
          echo "this worked"
          # Safely set the environment variable with diacritics
          FILES_TO_SEND=$(python3 -c "import urllib.parse, sys; print(urllib.parse.quote(sys.argv[1]))" "$FILES")
          echo "FILES_TO_SEND=$FILES_TO_SEND" >> $GITHUB_ENV

      - name: Debug Files to Send
        run: |
          cat files_to_send.txt
          echo "FILES_TO_SEND=$FILES_TO_SEND"
          DECODED_FILES=$(python3 -c "import urllib.parse, sys; print(urllib.parse.unquote(sys.argv[1]))" "$FILES_TO_SEND")
          echo "Decoded FILES_TO_SEND=$DECODED_FILES"
          
      - name: Trigger Send Resource
        env:
          GITHUB_TOKEN: ${{ secrets.MY_GITHUB_TOKEN }}
          FILES_TO_SEND: ${{ env.FILES_TO_SEND }}
        run: |
          # Decode the files before sending
          DECODED_FILES=$(python3 -c "import urllib.parse, sys; print(urllib.parse.unquote(sys.argv[1]))" "$FILES_TO_SEND")
          echo "Decoded FILES_TO_SEND=$DECODED_FILES"

          JSON_FILES=$(python3 -c "import json, sys; print(json.dumps(sys.argv[1]))" "$DECODED_FILES")

          if [ -z "$DECODED_FILES" ]; then
            echo "No files found to send. Exiting."
            exit 1
          fi
          curl -X POST \
          -H "Authorization: token $GITHUB_TOKEN" \
          -H "Accept: application/vnd.github.v3+json" \
          https://api.github.com/repos/UBB-resources-project/website_ubb/actions/workflows/add_resources.yml/dispatches \
          -d '{"ref":"workflow_resources", "inputs": {"files": "'"$JSON_FILES"'"}}'
