name: Add resources

on:
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  trigger_add_resources:
    runs-on: ubuntu-latest
    steps:
      - name: Check Out Repository
        uses: actions/checkout@v2
        with:
          fetch-depth: 0 
          
      - name: Set Files Variable
        id: files
        run: |
          echo "##[group]Extracting modified files"
          FILES=$(git diff --name-only ${{ github.event.pull_request.base.sha }} ${{ github.event.pull_request.head.sha }})
          echo "FILES=$FILES"
          echo "##[endgroup]"
          echo "::set-output name=files::$FILES"

          # Decode files using latin1 and utf-8
          DECODED_FILES=$(echo "$FILES" | python3 -c "import sys; print(sys.stdin.read().encode('latin1').decode('utf-8').strip())")
      
          # Print the decoded filenames for debugging
          echo "Decoded Files=$DECODED_FILES"
          
          curl -X POST \
            -H "Authorization: token ${{ secrets.MY_GITHUB_TOKEN }}" \
            -H "Accept: application/vnd.github.v3+json" \
            --data-urlencode "files=$DECODED_FILES" \
            https://api.github.com/repos/UBB-resources-project/website_ubb/actions/workflows/add_resources.yml/dispatches \
            -d "{\"ref\":\"workflow_resources\", \"inputs\": {\"files\": \"$DECODED_FILES\"}}"
