name: Trigger Add Resources

on:
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  trigger_add_resources:
    runs-on: ubuntu-latest
    steps:
      - name: Check Out Repository
        uses: actions/checkout@v2
        with:
          fetch-depth: 0 
          
      - name: Set Files Variable
        id: files
        run: |
          echo "##[group]Extracting modified files"
          FILES=$(git diff --name-only ${{ github.event.pull_request.base.sha }} ${{ github.event.pull_request.head.sha }})
          echo "FILES=$FILES"
          echo "##[endgroup]"
          echo "::set-output name=files::$FILES"
          
      - name: Trigger Send Resource
        env:
          GITHUB_TOKEN: ${{ secrets.MY_GITHUB_TOKEN }}
        run: |
          FILES_TO_SEND="${{ steps.files.outputs.files }}"
          echo "FILES_TO_SEND=${{ steps.files.outputs.files }}"
          echo "FILES_TO_SEND=${{ steps.files.outputs.files }}" > /dev/null
          cat /dev/null
          curl -X POST \
          -H "Authorization: token $GITHUB_TOKEN" \
          -H "Accept: application/vnd.github.v3+json" \
          https://api.github.com/repos/UBB-resources-project/website_ubb/actions/workflows/add_resources.yml/dispatches \
          -d '{"ref":"workflow_resources", "inputs": {"files": "'"$FILES_TO_SEND"'"}}'

