name: Detect Changes and Trigger Workflow

on:
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  detect_changes:
    runs-on: ubuntu-latest
    steps:
      - name: Check Out Repository
        uses: actions/checkout@v2

      - name: Detect Changed Files
        id: changes
        run: |
          FILES=$(git diff --name-only ${{ github.event.pull_request.base.sha }} ${{ github.event.pull_request.head.sha }} | jq -R -s -c 'split("\n") | map(select(length > 0))')          echo "Changed files: $FILES"
          echo "::set-output name=files::$FILES"

      - name: Trigger the Processing Workflow
        run: |
          curl -X POST \
            -H "Authorization: token ${{ secrets.MY_GITHUB_TOKEN }}" \
            -H "Accept: application/vnd.github.v3+json" \
            https://api.github.com/repos/UBB-resources-project/website_ubb/actions/workflows/add_resources.yml/dispatches \
            -d '{"ref":"workflow_resources", "inputs": {"files": ${{ steps.changes.outputs.files }}}}'
