name: Trigger Add Resources Workflow

on:
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  trigger_add_resources:
    runs-on: ubuntu-latest
    steps:
      - name: Check Out Repository
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Set Files Variable
        id: files
        run: |
          echo "##[group]Extracting modified files"
          FILES=$(git diff --name-only ${{ github.event.pull_request.head.sha }} ${{ github.sha }})
          echo "FILES=$FILES"
          echo "##[endgroup]"
          echo "::set-output name=files::$FILES"
      
      - name: Trigger Add Resources Workflow in Another Repository
        uses: benc-uk/workflow-dispatch@v1
        with:
          workflow: add_resources.yml  # Name of the workflow file in the triggered repo
          repo: UBB-resources-project/website_ubb  # Repository in which the workflow resides
          token: ${{ secrets.MY_GITHUB_TOKEN }}  # The token with access to the private repo
          ref: refs/heads/workflow_resources  # Branch in the target repo where the workflow exists
          inputs: '{"files": "${{ steps.files.outputs.files }}"}'
